import {
  AirVent,
  Armchair,
  Building2,
  BedDouble,
  CarFront,
  ChefHat,
  Clapperboard,
  Dumbbell,
  Flame,
  GlassWater,
  HandPlatter,
  Hotel,
  HouseWifi,
  LampCeiling,
  LayoutGrid,
  Leaf,
  Microwave,
  MonitorPlay,
  ParkingCircle,
  Refrigerator,
  Router,
  ShieldCheck,
  ShowerHead,
  Sofa,
  Sparkles,
  Trees,
  Tv,
  Users,
  UtensilsCrossed,
  WalletCards,
  WashingMachine,
  Waves,
  Wifi,
} from 'lucide-react';

const DEFAULT_META = { icon: Sparkles, colorClass: 'violet' };

export const AMENITY_META = {
  Parking: { icon: CarFront, colorClass: 'amber' },
  'Visitor Parking': { icon: ParkingCircle, colorClass: 'amber' },
  Lift: { icon: Building2, colorClass: 'indigo' },
  CCTV: { icon: MonitorPlay, colorClass: 'slate' },
  Security: { icon: ShieldCheck, colorClass: 'emerald' },
  Gym: { icon: Dumbbell, colorClass: 'rose' },
  Gymnasium: { icon: Dumbbell, colorClass: 'rose' },
  'Swimming Pool': { icon: Waves, colorClass: 'cyan' },
  'Club House': { icon: Users, colorClass: 'violet' },
  Clubhouse: { icon: Users, colorClass: 'violet' },
  Garden: { icon: Trees, colorClass: 'green' },
  'Children Play Area': { icon: Sparkles, colorClass: 'orange' },
  "Children's Play Area": { icon: Sparkles, colorClass: 'orange' },
  'Power Backup': { icon: Flame, colorClass: 'slate' },
  'Gas Pipeline': { icon: Flame, colorClass: 'orange' },
  'Rain Water Harvesting': { icon: GlassWater, colorClass: 'cyan' },
  'Waste Disposal': { icon: HandPlatter, colorClass: 'slate' },
  'Fire Safety': { icon: ShieldCheck, colorClass: 'red' },
  'Air Conditioner': { icon: AirVent, colorClass: 'cyan' },
  'Modular Kitchen': { icon: ChefHat, colorClass: 'amber' },
  Geyser: { icon: ShowerHead, colorClass: 'orange' },
  'RO System': { icon: GlassWater, colorClass: 'cyan' },
  Intercom: { icon: WalletCards, colorClass: 'indigo' },
  WiFi: { icon: Wifi, colorClass: 'blue' },
  TV: { icon: Tv, colorClass: 'violet' },
  Fridge: { icon: Refrigerator, colorClass: 'blue' },
  'Washing Machine': { icon: WashingMachine, colorClass: 'emerald' },
  Microwave: { icon: Microwave, colorClass: 'amber' },
  Sofa: { icon: Sofa, colorClass: 'rose' },
  Beds: { icon: BedDouble, colorClass: 'indigo' },
  'Jogging Track': { icon: Sparkles, colorClass: 'green' },
  'Indoor Games': { icon: Clapperboard, colorClass: 'violet' },
  'Multipurpose Hall': { icon: LayoutGrid, colorClass: 'slate' },
  'Senior Citizen Zone': { icon: Users, colorClass: 'emerald' },
  'Landscaped Garden': { icon: Leaf, colorClass: 'green' },
  'EV Charging': { icon: LampCeiling, colorClass: 'indigo' },
  'Terrace Garden': { icon: Trees, colorClass: 'green' },
  Cafeteria: { icon: UtensilsCrossed, colorClass: 'amber' },
  'Conference Room': { icon: LayoutGrid, colorClass: 'blue' },
  'Reception Lobby': { icon: Hotel, colorClass: 'slate' },
  '24x7 Water Supply': { icon: GlassWater, colorClass: 'cyan' },
  'Sewage Treatment Plant': { icon: Router, colorClass: 'slate' },
  'Pet Park': { icon: Sparkles, colorClass: 'orange' },
  'Yoga Deck': { icon: Armchair, colorClass: 'emerald' },
  'Mini Theatre': { icon: Clapperboard, colorClass: 'rose' },
  'Business Lounge': { icon: LayoutGrid, colorClass: 'blue' },
  'Sky Deck': { icon: HouseWifi, colorClass: 'indigo' },
};

export function getAmenityMeta(label) {
  return AMENITY_META[label] || DEFAULT_META;
}
