const SHARED_AMENITIES = [
  'Parking',
  'Security',
  'Power Backup',
];

export const PROJECT_TYPE_PROFILES = {
  Residential: {
    helper: 'Best for apartment, villa, and family township projects.',
    configurationOptions: ['1BHK', '2BHK', '3BHK', '4BHK', 'Villa', 'Penthouse'],
    amenities: [...SHARED_AMENITIES, 'Lift', 'Garden', 'Gym', 'Swimming Pool', 'Clubhouse', 'Children Play Area', 'Jogging Track', 'Indoor Games', 'Multipurpose Hall', 'Senior Citizen Zone', 'Landscaped Garden', 'EV Charging', 'Terrace Garden', 'Pet Park', 'Yoga Deck', 'Mini Theatre', '24x7 Water Supply', 'Sewage Treatment Plant'],
    labels: {
      developer: 'Developer / Builder Name',
      rera: 'RERA Number',
      possessionDate: 'Possession Date',
      pricingDescription: 'Capture launch pricing, apartment or villa sizes, and available home configurations.',
      configuration: 'Configuration Types',
      configurationHint: 'Choose the home formats available in this residential project.',
      addConfiguration: 'Add Configuration Field',
      areaRange: 'Apartment / Villa Area Range',
      areaRangePlaceholder: 'e.g. 650 - 1850 sq.ft',
      amenitiesDescription: 'Choose the lifestyle amenities available across the residential community.',
      totalTowers: 'Total Towers',
      totalUnits: 'Total Units',
      totalFloors: 'Floors Per Tower',
      openSpace: 'Open Space (%)',
      approvalAuthority: 'Approval Authority',
      additionalDescription: 'Residential scale, lifestyle planning, and authority approval details.',
      summaryLabel: 'Towers / Floors / Units',
      summaryValue: (project) => `${project.totalTowers || 0} / ${project.totalFloors || 0} / ${project.totalUnits || 0}`,
    },
  },
  Commercial: {
    helper: 'Tailored for office spaces, shops, retail, and business campuses.',
    configurationOptions: ['Office', 'Retail Shop', 'Showroom', 'Food Court', 'Clinic', 'Co-working'],
    amenities: [...SHARED_AMENITIES, 'Lift', 'Gym', 'Clubhouse', 'Swimming Pool', 'Cafeteria', 'Conference Room', 'Reception Lobby', 'Business Lounge', 'EV Charging', '24x7 Water Supply'],
    labels: {
      developer: 'Developer / Business Park Promoter',
      rera: 'RERA Number / Registration',
      possessionDate: 'Fit-Out / Possession Date',
      pricingDescription: 'Capture commercial pricing, saleable area ranges, and available unit formats.',
      configuration: 'Unit Types',
      configurationHint: 'Choose the commercial inventory formats offered in this project.',
      addConfiguration: 'Add Unit Type',
      areaRange: 'Carpet / Saleable Area Range',
      areaRangePlaceholder: 'e.g. 250 - 1800 sq.ft',
      amenitiesDescription: 'Choose the business-focused amenities available across the commercial campus.',
      totalTowers: 'Total Wings / Blocks',
      totalUnits: 'Total Shops / Offices',
      totalFloors: 'Total Floors',
      openSpace: 'Common Area (%)',
      approvalAuthority: 'Approval Authority / Local Body',
      additionalDescription: 'Commercial inventory scale, circulation planning, and approval details.',
      summaryLabel: 'Blocks / Floors / Units',
      summaryValue: (project) => `${project.totalTowers || 0} / ${project.totalFloors || 0} / ${project.totalUnits || 0}`,
    },
  },
  'Mixed Use': {
    helper: 'Works for projects that combine residential, retail, and office components.',
    configurationOptions: ['1BHK', '2BHK', '3BHK', 'Office', 'Retail Shop', 'Studio'],
    amenities: [...SHARED_AMENITIES, 'Lift', 'Garden', 'Gym', 'Swimming Pool', 'Clubhouse', 'Children Play Area', 'Jogging Track', 'Indoor Games', 'Multipurpose Hall', 'Landscaped Garden', 'EV Charging', 'Cafeteria', 'Conference Room', 'Reception Lobby', 'Business Lounge', 'Sky Deck', '24x7 Water Supply'],
    labels: {
      developer: 'Developer / Township Promoter',
      rera: 'RERA Number',
      possessionDate: 'Possession Date',
      pricingDescription: 'Capture mixed inventory pricing, carpet ranges, and the blend of available unit types.',
      configuration: 'Residential & Commercial Mix',
      configurationHint: 'Choose all residential and commercial formats available in this mixed-use project.',
      addConfiguration: 'Add Mix Type',
      areaRange: 'Area Range',
      areaRangePlaceholder: 'e.g. 350 - 2200 sq.ft',
      amenitiesDescription: 'Choose the combined lifestyle and business amenities offered in the project.',
      totalTowers: 'Total Towers / Blocks',
      totalUnits: 'Total Units / Inventories',
      totalFloors: 'Total Floors',
      openSpace: 'Open Space (%)',
      approvalAuthority: 'Approval Authority',
      additionalDescription: 'Capture the combined scale of the township, its inventory mix, and approval details.',
      summaryLabel: 'Blocks / Floors / Units',
      summaryValue: (project) => `${project.totalTowers || 0} / ${project.totalFloors || 0} / ${project.totalUnits || 0}`,
    },
  },
  Plots: {
    helper: 'Ideal for plotted layouts, land parcels, and gated plotting communities.',
    configurationOptions: ['Residential Plot', 'Corner Plot', 'NA Plot', 'Villa Plot', 'Farm Plot', 'Commercial Plot'],
    amenities: ['Parking', 'Security', 'Garden', 'Children Play Area', 'Clubhouse', 'Power Backup', 'Jogging Track', 'Landscaped Garden', 'EV Charging', 'Terrace Garden', 'Pet Park', '24x7 Water Supply', 'Sewage Treatment Plant'],
    labels: {
      developer: 'Developer / Layout Promoter',
      rera: 'Layout Approval / RERA Number',
      possessionDate: 'Registration / Handover Date',
      pricingDescription: 'Capture plot pricing, plot-size ranges, and the different plot formats on offer.',
      configuration: 'Plot Types',
      configurationHint: 'Choose the kinds of plots available in this layout.',
      addConfiguration: 'Add Plot Type',
      areaRange: 'Plot Size Range',
      areaRangePlaceholder: 'e.g. 1200 - 3000 sq.ft',
      amenitiesDescription: 'Choose the site infrastructure and community amenities available in the plotted layout.',
      totalTowers: 'Total Sectors / Phases',
      totalUnits: 'Total Plots',
      totalFloors: 'Development Stages',
      openSpace: 'Roads / Open Space (%)',
      approvalAuthority: 'Approval Authority / Layout Sanction',
      additionalDescription: 'Capture phase planning, total plots, development stages, and approval details.',
      summaryLabel: 'Phases / Stages / Plots',
      summaryValue: (project) => `${project.totalTowers || 0} / ${project.totalFloors || 0} / ${project.totalUnits || 0}`,
    },
  },
};

const fallbackProfile = {
  helper: 'Choose a project type to tailor labels, options, and helper text.',
  configurationOptions: ['1BHK', '2BHK', '3BHK', 'Villa', 'Plot', 'Office', 'Retail Shop'],
  amenities: ['Parking', 'Lift', 'Security', 'Garden', 'Gym', 'Swimming Pool', 'Clubhouse', 'Children Play Area', 'Power Backup', 'Jogging Track', 'Indoor Games', 'Multipurpose Hall', 'Landscaped Garden', 'EV Charging', 'Terrace Garden', 'Cafeteria', 'Conference Room', 'Reception Lobby', '24x7 Water Supply'],
  labels: {
    developer: 'Developer / Builder Name',
    rera: 'RERA Number',
    possessionDate: 'Possession Date',
    pricingDescription: 'Capture pricing band, area range, and available unit types.',
    configuration: 'Configuration Types',
    configurationHint: 'Choose the main unit formats available in this project.',
    addConfiguration: 'Add Configuration Field',
    areaRange: 'Area Range',
    areaRangePlaceholder: 'e.g. 500 - 1200 sq.ft',
    amenitiesDescription: 'Choose the amenities available across the project.',
    totalTowers: 'Total Towers',
    totalUnits: 'Total Units',
    totalFloors: 'Total Floors',
    openSpace: 'Open Space (%)',
    approvalAuthority: 'Approval Authority',
    additionalDescription: 'Project scale, open space, and authority approval details.',
    summaryLabel: 'Towers / Floors / Units',
    summaryValue: (project) => `${project.totalTowers || 0} / ${project.totalFloors || 0} / ${project.totalUnits || 0}`,
  },
};

export function getProjectTypeProfile(projectType) {
  return PROJECT_TYPE_PROFILES[projectType] || fallbackProfile;
}
